development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mjmmqzkwfkczpv:bf7fc500130b4251de71ac5e52117f194b46e5f8e8bcdd2e63abd1a56a153062@ec2-54-83-19-244.compute-1.amazonaws.com:5432/d4hsk30d90g81h
  channel_prefix: superapp_production
